# Generated by Django 5.0.1 on 2024-05-02 18:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_answer_uuid_alter_category_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('8c4e33e6-9851-41c3-a3b4-9973dd443a9a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('8c4e33e6-9851-41c3-a3b4-9973dd443a9a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('8c4e33e6-9851-41c3-a3b4-9973dd443a9a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
