# Generated by Django 5.0.1 on 2024-05-07 10:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_basemodel_remove_question_category_delete_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('8a8fc01b-2662-45d5-894a-133e99a2f50d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
