# Generated by Django 5.0.1 on 2024-05-07 17:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_basemodel_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('faa43016-3ca4-4916-b19a-e5cd71d4c61e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
