# Generated by Django 5.0.1 on 2024-05-09 10:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_alter_basemodel_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('73cac7ec-760f-4f76-b636-94a47717350a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
