# Generated by Django 5.0.1 on 2024-05-09 10:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_alter_basemodel_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a6855279-9862-4974-a316-4a9e4cf02215'), editable=False, primary_key=True, serialize=False),
        ),
    ]
