# Generated by Django 5.0.1 on 2024-05-07 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeScanner', '0004_remove_resumescanner_resume_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumescanner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 7, 17, 48, 53, 838439, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
