# Generated by Django 5.0.1 on 2024-04-18 18:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='options',
            new_name='question',
        ),
        migrations.AlterField(
            model_name='answer',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('2cfd3c20-cd2d-4eed-bc92-48052ee728e1'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('2cfd3c20-cd2d-4eed-bc92-48052ee728e1'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('2cfd3c20-cd2d-4eed-bc92-48052ee728e1'), editable=False, primary_key=True, serialize=False),
        ),
    ]
