# Generated by Django 5.0.1 on 2024-05-09 18:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_answer_category_question_delete_basemodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('870d3c9d-fdfb-454d-a00d-6d42a366493e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('870d3c9d-fdfb-454d-a00d-6d42a366493e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('870d3c9d-fdfb-454d-a00d-6d42a366493e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
