# Generated by Django 5.0.6 on 2024-05-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_interview_questions_delete_full_stack_questions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tech_field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='interview',
            name='field_choice',
            field=models.CharField(choices=[('MERN', 'MERN'), ('Java', 'Java'), ('Python', 'Python'), ('Full Stack', 'Full Stack')], max_length=50),
        ),
    ]
