# Generated by Django 5.0.6 on 2024-05-22 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0005_tech_field_alter_interview_field_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='feedback',
            new_name='chat',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='date',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='score',
        ),
    ]
