# Generated by Django 5.0.1 on 2024-05-07 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumeScanner', '0003_remove_resumescanner_resume_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumescanner',
            name='resume_id',
        ),
    ]
