# Generated by Django 5.0.1 on 2024-05-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_full_stack_questions_java_questions_python_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview_questions',
            fields=[
                ('q_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField(blank=True, null=True)),
                ('question_type', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Full_Stack_Questions',
        ),
        migrations.DeleteModel(
            name='Java_Questions',
        ),
        migrations.DeleteModel(
            name='MERN_Questions',
        ),
        migrations.DeleteModel(
            name='Python_Questions',
        ),
    ]
